/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sk_shootingrange.fld_Poligon;

import com.mycompany.sk_shootingrange.fld_Ammo.SqlAmmoProcess;
import com.mycompany.sk_shootingrange.fld_Costumer.SqlCostumerProcess;
import com.mycompany.sk_shootingrange.fld_Employee.SqlEmployeeProcess;
import com.mycompany.sk_shootingrange.fld_Weapons.SqlWeaponProcess;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author semih
 */
public class frmPoligon extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPoligon.class.getName());

    /**
     * Creates new form frmPoligon
     */
    public frmPoligon() {
        initComponents();
        
        jPanel1.setVisible(false);
    }
    
    public frmPoligon(String id) {
        initComponents();
        
        this.setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        
        spnAmmoCount.setModel(model);
        model.setStepSize(1);
        model.setMinimum(0);
        model.setMaximum(0);
        model.setValue(0);
        
        this.id = id;
        admin = eProcess.isAdmin(id);
    }
    
    private String id = "";
    private boolean admin = false;
    private SpinnerNumberModel model = new SpinnerNumberModel();
    private Poligon poligon = new Poligon();
    private SqlPoligonProcess process = new SqlPoligonProcess();
    private SqlAmmoProcess aProcess = new SqlAmmoProcess();
    private SqlEmployeeProcess eProcess = new SqlEmployeeProcess();
    private SqlCostumerProcess cProcess = new SqlCostumerProcess();
    private SqlWeaponProcess wProcess = new SqlWeaponProcess();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        txtCostumerID = new javax.swing.JTextField();
        txtEmployeeID = new javax.swing.JTextField();
        txtWeponsID = new javax.swing.JTextField();
        spnAmmoCount = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txtAmmoID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        chkUserInfo = new javax.swing.JCheckBox();
        chkSignature = new javax.swing.JCheckBox();
        chkStudy = new javax.swing.JCheckBox();
        txtPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Poligon");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Müşteri TC : ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Çalışan TC : ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Silah Seri No : ");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(328, 44));
        jPanel2.setMinimumSize(new java.awt.Dimension(328, 44));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("Siparişi Tamamla");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setMaximumSize(new java.awt.Dimension(72, 32));
        btnAdd.setMinimumSize(new java.awt.Dimension(72, 32));
        btnAdd.setPreferredSize(new java.awt.Dimension(72, 32));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtCostumerID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCostumerID.setMaximumSize(new java.awt.Dimension(254, 30));
        txtCostumerID.setMinimumSize(new java.awt.Dimension(254, 30));
        txtCostumerID.setPreferredSize(new java.awt.Dimension(254, 30));

        txtEmployeeID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmployeeID.setMaximumSize(new java.awt.Dimension(254, 30));
        txtEmployeeID.setMinimumSize(new java.awt.Dimension(254, 30));
        txtEmployeeID.setPreferredSize(new java.awt.Dimension(254, 30));

        txtWeponsID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtWeponsID.setMaximumSize(new java.awt.Dimension(254, 30));
        txtWeponsID.setMinimumSize(new java.awt.Dimension(254, 30));
        txtWeponsID.setPreferredSize(new java.awt.Dimension(254, 30));

        spnAmmoCount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnAmmoCount.setMaximumSize(new java.awt.Dimension(254, 26));
        spnAmmoCount.setMinimumSize(new java.awt.Dimension(254, 26));
        spnAmmoCount.setPreferredSize(new java.awt.Dimension(254, 26));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Atılan Mermi : ");

        txtAmmoID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAmmoID.setToolTipText("Mühimmat ID girip 'ENTER' yaparak mermi bilgisini getirebilirsiniz.");
        txtAmmoID.setMaximumSize(new java.awt.Dimension(254, 30));
        txtAmmoID.setMinimumSize(new java.awt.Dimension(254, 30));
        txtAmmoID.setPreferredSize(new java.awt.Dimension(254, 30));
        txtAmmoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmmoIDActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mühimmat ID : ");

        chkUserInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkUserInfo.setText("Kullanıcı Bilgilendirildi");
        chkUserInfo.setContentAreaFilled(false);
        chkUserInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        chkSignature.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkSignature.setText("Kullanıcı Tüm Şartları Oku, İmzaladı, Kabul Etti");
        chkSignature.setContentAreaFilled(false);
        chkSignature.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        chkStudy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkStudy.setText("Eğitim Verildi");
        chkStudy.setContentAreaFilled(false);
        chkStudy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrice.setMaximumSize(new java.awt.Dimension(254, 30));
        txtPrice.setMinimumSize(new java.awt.Dimension(254, 30));
        txtPrice.setPreferredSize(new java.awt.Dimension(254, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Alınan Ücret : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWeponsID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCostumerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(chkSignature, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkUserInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkStudy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spnAmmoCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAmmoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCostumerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtWeponsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAmmoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkUserInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSignature)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkStudy)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (eProcess.isThereEmployee(txtEmployeeID.getText())) {
            poligon.setEmployee(eProcess.getEmployee(txtEmployeeID.getText()));
        } else {
            JOptionPane.showMessageDialog(null, "Çalışan TC sistemde mevcut değil!","Var Olmayan ID",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (cProcess.isThereCostumer(txtCostumerID.getText())) {
            poligon.setCostumer(cProcess.getCostumer(txtCostumerID.getText()));
        } else {
            JOptionPane.showMessageDialog(null, "Müşteri TC sistemde mevcut değil!","Var Olmayan ID",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (wProcess.isThereID(txtWeponsID.getText())) {
            poligon.setWeapon(wProcess.getWeapon(txtWeponsID.getText()));
            
            if(!poligon.getWeapon().isActive()){
                JOptionPane.showMessageDialog(null, "Kullanılmak istenen silah aktif değil.\nAçıklaması : " + poligon.getWeapon().getComment(), "Aktif Olmayan Silah", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Silah seri no sistemde mevcut değil!","Var Olmayan ID",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            if (aProcess.isThereID(Integer.parseInt(txtAmmoID.getText()))) {
                poligon.setAmmo(aProcess.getAmmo(Integer.parseInt(txtAmmoID.getText())));
            } else {
                JOptionPane.showMessageDialog(null, "Mühimmat ID sistemde mevcut değil!","Var Olmayan ID",JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hatalı veri girişi sağlandı.\nLütfen tekrar deneyin.","Hatalı Değer",JOptionPane.WARNING_MESSAGE);
        }
        
        if (poligon.chkSetPrice(txtPrice.getText()) && chkUserInfo.isSelected() && chkSignature.isSelected() && (int) spnAmmoCount.getValue() > 0 && poligon.getAmmo().getStock() >= (int) spnAmmoCount.getValue()) {
            poligon.setStudy(chkStudy.isSelected());
            poligon.setUserInfo(chkUserInfo.isSelected());
            poligon.setUserSignature(chkSignature.isSelected());
            poligon.setCount((int) spnAmmoCount.getValue());
            
            if (process.addPoligon(poligon)) {
                JOptionPane.showMessageDialog(null, "İşlem başarıyla gerçekleşti.","Tamamlanan İşlem",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "İşlem gerçekleşirken hata ile karşılaşıldı.\nİşlem gerçekleşmedi.","İşlem Tamamlanmadı",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtAmmoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmmoIDActionPerformed
        // TODO add your handling code here:
        model.setValue(0);
        try {
            if (aProcess.isThereID(Integer.parseInt(txtAmmoID.getText()))) {
                poligon.setAmmo(aProcess.getAmmo(Integer.parseInt(txtAmmoID.getText())));
                model.setMaximum(poligon.getAmmo().getStock());
                return;
            }
            JOptionPane.showMessageDialog(null, "Mühimmat ID sistemde mevcut değil!","Var Olmayan ID",JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hatalı veri girişi sağlandı.\nLütfen tekrar deneyin.","Hatalı Değer",JOptionPane.WARNING_MESSAGE);
        }
        model.setMaximum(0);
    }//GEN-LAST:event_txtAmmoIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPoligon().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JCheckBox chkSignature;
    private javax.swing.JCheckBox chkStudy;
    private javax.swing.JCheckBox chkUserInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner spnAmmoCount;
    private javax.swing.JTextField txtAmmoID;
    private javax.swing.JTextField txtCostumerID;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtWeponsID;
    // End of variables declaration//GEN-END:variables
}
